export const radiantShaderCatalog = [
  { id: "flow-field", path: "flow-field/index.html", title: "Flow Field with Particle Trails", scheme: null },
  { id: "topographic", path: "topographic/index.html", title: "Topographic Contour Map", scheme: null },
  { id: "generative-tree", path: "generative-tree/index.html", title: "Generative Branching Tree", scheme: null },
  { id: "strange-attractor", path: "strange-attractor/index.html", title: "Strange Attractor (Lorenz)", scheme: null },
  { id: "pendulum-wave", path: "pendulum-wave/index.html", title: "Pendulum Wave", scheme: null },
  { id: "phyllotaxis", path: "phyllotaxis/index.html", title: "Phyllotaxis Spiral", scheme: null },
  { id: "fluid-amber", path: "fluid-amber/index.html", title: "Fluid Amber", scheme: null },
  { id: "champagne-fizz", path: "champagne-fizz/index.html", title: "Champagne Fizz", scheme: null },
  { id: "sugar-glass", path: "sugar-glass/index.html", title: "Sugar Glass", scheme: null },
  { id: "resonant-strings", path: "resonant-strings/index.html", title: "Resonant Strings", scheme: null },
  { id: "chladni-resonance", path: "chladni-resonance/index.html", title: "Chladni Resonance", scheme: null },
  { id: "kinetic-grid", path: "kinetic-grid/index.html", title: "Kinetic Grid", scheme: null },
  { id: "strobe-geometry", path: "strobe-geometry/index.html", title: "Strobe Geometry", scheme: null },
  { id: "laser-labyrinth", path: "laser-labyrinth/index.html", title: "Laser Labyrinth", scheme: null },
  { id: "bass-ripple", path: "bass-ripple/index.html", title: "Bass Ripple", scheme: null },
  { id: "ink-dissolve", path: "ink-dissolve/index.html", title: "Ink Dissolve", scheme: null },
  { id: "sequin-wave", path: "sequin-wave/index.html", title: "Sequin Wave", scheme: null },
  { id: "gilt-mosaic", path: "gilt-mosaic/index.html", title: "Gilt Mosaic", scheme: null },
  { id: "gilded-fracture", path: "gilded-fracture/index.html", title: "Gilded Fracture", scheme: null },
  { id: "radiant-geometry", path: "radiant-geometry/index.html", title: "Radiant Geometry", scheme: null },
  { id: "golden-throne", path: "golden-throne/index.html", title: "Golden Throne", scheme: null },
  { id: "sacred-strange", path: "sacred-strange/index.html", title: "Sacred Strange", scheme: null },
  { id: "tropical-heat", path: "tropical-heat/index.html", title: "Tropical Heat", scheme: null },
  { id: "neon-drip", path: "neon-drip/index.html", title: "Neon Drip", scheme: null },
  { id: "voltage-arc", path: "voltage-arc/index.html", title: "Voltage Arc", scheme: null },
  { id: "moonlit-ripple", path: "moonlit-ripple/index.html", title: "Moonlit Ripple", scheme: "blue" },
  { id: "eclipse-glow", path: "eclipse-glow/index.html", title: "Eclipse Glow", scheme: null },
  { id: "diamond-caustics", path: "diamond-caustics/index.html", title: "Diamond Caustics", scheme: null },
  { id: "rain-on-glass", path: "rain-on-glass/index.html", title: "Rain on Glass", scheme: null },
  { id: "rain-umbrella", path: "rain-umbrella/index.html", title: "Rain on Umbrella", scheme: null },
  { id: "metamorphosis", path: "metamorphosis/index.html", title: "Metamorphosis", scheme: null },
  { id: "artpop-iridescence", path: "artpop-iridescence/index.html", title: "Artpop Iridescence", scheme: null },
  { id: "silk-groove", path: "silk-groove/index.html", title: "Silk Groove", scheme: null },
  { id: "gilt-thread", path: "gilt-thread/index.html", title: "Gilt Thread", scheme: null },
  { id: "event-horizon", path: "event-horizon/index.html", title: "Event Horizon", scheme: null },
  { id: "burning-film", path: "burning-film/index.html", title: "Burning Film", scheme: null },
  { id: "vertigo", path: "vertigo/index.html", title: "Vertigo", scheme: null },
  { id: "stardust-veil", path: "stardust-veil/index.html", title: "Stardust Veil", scheme: null },
  { id: "silk-cascade", path: "silk-cascade/index.html", title: "Silk Cascade", scheme: null },
  { id: "smolder", path: "smolder/index.html", title: "Smolder", scheme: null },
  { id: "signal-decay", path: "signal-decay/index.html", title: "Signal Decay", scheme: null },
  { id: "neon-revival", path: "neon-revival/index.html", title: "Neon Revival", scheme: null },
  { id: "lipstick-smear", path: "lipstick-smear/index.html", title: "Lipstick Smear", scheme: null },
  { id: "glitter-storm", path: "glitter-storm/index.html", title: "Glitter Storm", scheme: null },
  { id: "rubber-reality", path: "rubber-reality/index.html", title: "Rubber Reality", scheme: null },
  { id: "magma-core", path: "magma-core/index.html", title: "Magma Core", scheme: null },
  { id: "clockwork-mind", path: "clockwork-mind/index.html", title: "Clockwork Mind", scheme: null },
  { id: "edge-of-chaos", path: "edge-of-chaos/index.html", title: "Edge of Chaos", scheme: null },
  { id: "spark-chamber", path: "spark-chamber/index.html", title: "Spark Chamber", scheme: null },
  { id: "shifting-veils", path: "shifting-veils/index.html", title: "Shifting Veils", scheme: null },
  { id: "crystal-lattice", path: "crystal-lattice/index.html", title: "Crystal Lattice", scheme: null },
  { id: "kaleidoscope-runway", path: "kaleidoscope-runway/index.html", title: "Kaleidoscope Runway", scheme: null },
  { id: "digital-rain", path: "digital-rain/index.html", title: "Digital Rain", scheme: null },
  { id: "neon-drive", path: "neon-drive/index.html", title: "Neon Drive", scheme: null },
  { id: "liquid-gold", path: "liquid-gold/index.html", title: "Liquid Gold", scheme: null },
  { id: "aurora-veil", path: "aurora-veil/index.html", title: "Aurora Veil", scheme: null },
  { id: "bioluminescence", path: "bioluminescence/index.html", title: "Bioluminescence", scheme: "blue" },
  { id: "gothic-filigree", path: "gothic-filigree/index.html", title: "Gothic Filigree", scheme: null },
  { id: "laser-precision", path: "laser-precision/index.html", title: "Laser Precision", scheme: null },
  { id: "magnetic-sand", path: "magnetic-sand/index.html", title: "Magnetic Sand", scheme: null },
  { id: "woven-radiance", path: "woven-radiance/index.html", title: "Woven Radiance", scheme: null },
  { id: "jazz-chaos", path: "jazz-chaos/index.html", title: "Jazz Chaos", scheme: null },
  { id: "thunder-sermon", path: "thunder-sermon/index.html", title: "Thunder Sermon", scheme: null },
  { id: "vinyl-grooves", path: "vinyl-grooves/index.html", title: "Vinyl Grooves", scheme: null },
  { id: "vintage-static", path: "vintage-static/index.html", title: "Vintage Static", scheme: null },
  { id: "torn-paper", path: "torn-paper/index.html", title: "Torn Paper", scheme: null },
  { id: "polaroid-burn", path: "polaroid-burn/index.html", title: "Polaroid Burn", scheme: null },
  { id: "scream-wave", path: "scream-wave/index.html", title: "Scream Wave", scheme: null },
  { id: "ink-calligraphy", path: "ink-calligraphy/index.html", title: "Ink Calligraphy", scheme: null },
  { id: "velvet-spotlight", path: "velvet-spotlight/index.html", title: "Velvet Spotlight", scheme: null },
  { id: "murmuration", path: "murmuration/index.html", title: "Murmuration", scheme: null },
  { id: "tesseract-shadow", path: "tesseract-shadow/index.html", title: "Tesseract Shadow", scheme: null },
  { id: "moire-interference", path: "moire-interference/index.html", title: "Moiré Interference", scheme: null },
  { id: "phase-transition", path: "phase-transition/index.html", title: "Phase Transition", scheme: null },
  { id: "magnetic-field", path: "magnetic-field/index.html", title: "Magnetic Field", scheme: null },
  { id: "aurora-curtain", path: "aurora-curtain/index.html", title: "Aurora Curtain", scheme: null },
  { id: "vortex", path: "vortex/index.html", title: "Vortex", scheme: null },
  { id: "chromatic-bloom", path: "chromatic-bloom/index.html", title: "Chromatic Bloom", scheme: null },
  { id: "lens-whisper", path: "lens-whisper/index.html", title: "Lens Whisper", scheme: null },
  { id: "luminous-silt", path: "luminous-silt/index.html", title: "Luminous Silt", scheme: null },
  { id: "synth-ribbon", path: "synth-ribbon/index.html", title: "Synth Ribbon", scheme: null },
  { id: "hologram-glitch", path: "hologram-glitch/index.html", title: "Hologram Glitch", scheme: null },
  { id: "shattered-plains", path: "shattered-plains/index.html", title: "Shattered Plains", scheme: null },
  { id: "painted-strata", path: "painted-strata/index.html", title: "Painted Strata", scheme: null },
  { id: "feedback-loop", path: "feedback-loop/index.html", title: "Feedback Loop", scheme: null },
  { id: "dither-gradient", path: "dither-gradient/index.html", title: "Dither Gradient", scheme: null },
  { id: "analog-drift", path: "analog-drift/index.html", title: "Analog Drift", scheme: null },
];
