from __future__ import annotations

import json
import os

import requests
from dotenv import load_dotenv

from lib.groq_json import parse_groq_json


GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"
DEFAULT_GROQ_MODEL = "llama-3.3-70b-versatile"
BANNED_PHRASES = (
    "repo-owned",
    "stream pipeline",
    "generated by",
)

load_dotenv()


def _sanitize_text(value, max_length=None, preserve_newlines=False):
    if not isinstance(value, str):
        return ""
    
    if preserve_newlines:
        cleaned = value.strip()
    else:
        cleaned = " ".join(value.split()).strip()
        
    for phrase in BANNED_PHRASES:
        cleaned = cleaned.replace(phrase, "").replace(phrase.title(), "").strip(" -|:")
    if max_length and len(cleaned) > max_length:
        cleaned = cleaned[:max_length].rstrip(" ,|-:")
    return cleaned


def generate_stream_copy(plan, fallback_metadata, preview=False):
    if os.getenv("USE_GROQ_COPY", "0").strip().lower() not in {"1", "true", "yes", "on"}:
        return None
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        return None

    model = os.getenv("GROQ_MODEL", DEFAULT_GROQ_MODEL).strip() or DEFAULT_GROQ_MODEL
    profile = plan["profile"]
    prompt_payload = {
        "profile_id": plan["profile_id"],
        "profile_name": profile["display_name"],
        "headline": profile["title_parts"]["headline"],
        "descriptor": profile["title_parts"]["descriptor"],
        "thumbnail_title": profile["thumbnail_parts"]["title"],
        "thumbnail_subtitle": profile["thumbnail_parts"]["subtitle"],
        "channel_prefix": profile["title_parts"].get("channel_prefix", "Symphony.Station"),
        "daypart": plan["daypart"],
        "season": plan["season"],
        "render_mode": plan["render_mode"],
        "preview": preview,
        "core_ambience": [layer["name"] for layer in plan["layers"] if layer.get("role") in ("bed",)],
        "atmospheric_layers": [layer["name"] for layer in plan["layers"] if layer.get("role") in ("secondary", "noise", "binaural")],
        "dynamic_accents": [layer["name"] for layer in plan["layers"] if layer.get("role") in ("accent",)],
        "tags": plan["tags"][:8],
        "fallback_title": fallback_metadata["title"],
        "fallback_description": fallback_metadata["description"],
        "fallback_thumbnail_title": fallback_metadata["thumbnail_title"],
        "fallback_thumbnail_subtitle": fallback_metadata["thumbnail_subtitle"],
    }

    system_prompt = (
        "You are an elite YouTube viral copywriter generating livestream metadata for aesthetic sleep, study, and ambience channels. "
        "Return JSON only with keys: title, description, thumbnail_title, thumbnail_subtitle, badge_text. "
        "Rules for Title: Extremely catchy, emotional hook, front-load the most important vibe or scenario. Use a divider ( | ) and include benefits (e.g. 🌧️ Midnight Rain | Deep Focus & Sleep). Keep under 85 characters. No all-caps spam. \n"
        "Rules for Description: Write an immersive 2-paragraph intro setting the serene scene based on the 'headline', 'daypart', and 'core_ambience'. Then, follow EXACTLY this layout for the rest of the description:\n\n"
        "[Immersive Intro Paragraph 1]\n\n"
        "[Immersive Intro Paragraph 2 about it being a digital escape for studying, sleeping, etc.]\n\n"
        "🎧 The Soundscape\n"
        "    Core Ambience: [Describe the literal actual sounds provided in 'core_ambience' payload].\n"
        "    Atmospheric Textures: [Describe the literal actual sounds provided in 'atmospheric_layers' payload].\n"
        "    Dynamic Details: [Describe the literal actual sounds provided in 'dynamic_accents' payload].\n\n"
        "✨ Join Our Journey to 10,000\n"
        "We are building a community of peace-seekers and deep-thinkers. If this stream helped you find a moment of calm today, consider subscribing and joining the family. We’re on the road to 10k subscribers, and every soul in this community makes the vibe better.\n\n"
        "🔔 Turn on notifications to never miss a moment of serenity.\n"
        "🕒 Ways to Use This Stream\n"
        "    Deep Work: Perfect for blocking out office distractions.\n"
        "    Meditation: A natural metronome for your breathing exercises.\n"
        "    Sleep Aid: Let the white noise guide you into REM.\n\n"
        "#[relevant_tag_1] #[relevant_tag_2] #[relevant_tag_3] #meditationmusic #studyambience #10ksubscribers \n\n"
        "IMPORTANT SOUNDSCAPE RULE: Under '🎧 The Soundscape', you MUST NOT invent sounds. You MUST explicitly list out the actual names of the sounds given to you in the payload's 'core_ambience', 'atmospheric_layers', and 'dynamic_accents' and stylize them. Do not assume 'Living River' if it is not present. \n"
        "Thumbnail Title: 2-3 punchy words (e.g., 'Night Rain'). \n"
        "Thumbnail Subtitle: Short vibe descriptor. \n"
        "Badge Text: E.g., 'LIVE 24/7' or 'STUDY'. No internal tooling language or generation mentions ever. \n"
        "CRITICAL: Produce valid JSON. You MUST escape all newlines inside your strings as \\n otherwise parsing will fail. Do not use raw carriage returns."
    )
    user_prompt = json.dumps(prompt_payload, ensure_ascii=True)

    try:
        response = requests.post(
            GROQ_API_URL,
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type":  "application/json",
            },
            json={
                "model":       model,
                "temperature": 0.35,
                "max_tokens":  1500,   # Descriptions are long; avoid truncated/broken JSON
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user",   "content": user_prompt},
                ],
            },
            timeout=60,
        )
        response.raise_for_status()
        payload = response.json()
        content = payload["choices"][0]["message"]["content"]
        parsed = parse_groq_json(content)

    except requests.HTTPError as exc:
        print(f"[GroqCopy] HTTP error from Groq API: {exc} — using fallback metadata.")
        return None
    except json.JSONDecodeError as exc:
        print(f"[GroqCopy] JSON parse error in Groq response: {exc} — using fallback metadata.")
        return None
    except Exception as exc:
        print(f"[GroqCopy] Unexpected error: {exc} — using fallback metadata.")
        return None

    title = _sanitize_text(parsed.get("title"), max_length=100) or fallback_metadata["title"]
    description = _sanitize_text(parsed.get("description"), preserve_newlines=True) or fallback_metadata["description"]
    thumbnail_title = _sanitize_text(parsed.get("thumbnail_title"), max_length=36) or fallback_metadata["thumbnail_title"]
    thumbnail_subtitle = _sanitize_text(parsed.get("thumbnail_subtitle"), max_length=72) or fallback_metadata["thumbnail_subtitle"]
    badge_text = _sanitize_text(parsed.get("badge_text"), max_length=28) or fallback_metadata["badge_text"]

    return {
        "title":              title,
        "description":        description,
        "thumbnail_title":    thumbnail_title,
        "thumbnail_subtitle": thumbnail_subtitle,
        "badge_text":         badge_text,
    }

